import type { PackageRow, ProjectRow, SessionRow } from './supabase';

// Spaceship / supply-chain scenario for the public demo dashboard.
// Missions = projects, crews/ships = actors, supply manifests = packages.

const now = Date.now();
const minutesAgo = (m: number) => new Date(now - m * 60_000).toISOString();
const hoursAgo = (h: number) => new Date(now - h * 3_600_000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 86_400_000).toISOString();

export const MOCK_PROJECTS: ProjectRow[] = [
  {
    id: 'proj_oort_resupply',
    name: 'Oort Resupply Corridor',
    description: 'Primary fleet logistics — long-haul fuel, hull plating, and medical crates along the outer belt',
    created_at: daysAgo(64),
    archived_at: null,
  },
  {
    id: 'proj_kepler_mining',
    name: 'Kepler-442b Mining Run',
    description: 'Rare-earth extraction and ore transport back to Ceres refinery',
    created_at: daysAgo(41),
    archived_at: null,
  },
  {
    id: 'proj_ceres_station',
    name: 'Ceres Station Ops',
    description: 'Central hub maintenance, dry-dock scheduling, and crew rotation',
    created_at: daysAgo(88),
    archived_at: null,
  },
  {
    id: 'proj_europa_survey',
    name: 'Europa Deep Survey',
    description: 'Subsurface ice-ocean research mission — sample returns, sonar arrays, ROV telemetry',
    created_at: daysAgo(23),
    archived_at: null,
  },
  {
    id: 'proj_titan_relay',
    name: 'Titan Relay Network',
    description: 'Comms satellite constellation deployment and uplink maintenance',
    created_at: daysAgo(17),
    archived_at: null,
  },
  {
    id: 'proj_helios_freight',
    name: 'Helios Freight Line',
    description: 'Solar-orbit cargo runs (decommissioned after Helios-3 incident)',
    created_at: daysAgo(210),
    archived_at: daysAgo(45),
  },
];

interface PkgSpec {
  id: string;
  project_id: string;
  title: string;
  description?: string;
  status?: string;
  actor_type?: 'human' | 'agent';
  actor_id?: string;
  topic?: string | null;
  artifact_type?: string | null;
  significance?: number;
  handoff_note?: string | null;
  decisions?: string[];
  questions?: string[];
  tags?: string[];
  created_at: string;
}

const PKGS: PkgSpec[] = [
  // ========== Oort Resupply Corridor (largest cluster — renders as brain core)
  {
    id: 'pkg_oort_001',
    project_id: 'proj_oort_resupply',
    title: '[KEY 10] Manifest 4418 LOADED — deuterium cells + hull plating to Europa Dry Dock',
    description:
      'Full payload locked in Bay 3 and Bay 4 of the Nightingale. 40 tons deuterium fuel cells, 180 units stabilized hull plating (gamma-rated), 12 crates cryo-med. ETA Europa 7 days 4 hours at 0.42c cruise. Pilot Nakamura signed off on cargo weight distribution.',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'chief_vega',
    topic: 'logistics',
    artifact_type: 'milestone',
    significance: 10,
    handoff_note:
      'Europa Dry Dock expects arrival window 0800–1400 station time. Coordinate unload crew with Commander Shepard before departure.',
    decisions: [
      'Route via Lagrange-4 skip instead of direct — saves 1.2 tons reaction mass at cost of 6 extra hours',
      'Bay 3 temperature held at -40C for cryo-med integrity, overriding default cargo-bay setting',
    ],
    questions: ['Confirm Europa has capacity to receive all 180 hull plates in single delivery, or stage across two?'],
    tags: ['logistics', 'priority'],
    created_at: minutesAgo(22),
  },
  {
    id: 'pkg_oort_002',
    project_id: 'proj_oort_resupply',
    title: '[KEY 9] Pilot reported graviton turbulence at Lagrange-4 — rerouting via L-5',
    description:
      'Autobot Lumen detected unexpected gravitational shear on approach to L-4 skip point. Current nav model does not account for Saturn ring-system perturbations at this declination. Rerouting adds 8 hours but keeps hull stress within spec.',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'nav_system_kepler',
    topic: 'navigation',
    artifact_type: 'analysis',
    significance: 9,
    handoff_note: 'Log anomaly for nav model retraining. Chief Vega to file ops report with Ceres.',
    decisions: ['Accept 8h delay rather than push through turbulence — hull rated 2.1g peak, shear was pulling 1.9g'],
    tags: ['navigation', 'safety'],
    created_at: hoursAgo(3),
  },
  {
    id: 'pkg_oort_003',
    project_id: 'proj_oort_resupply',
    title: '[SIG 8] Crew complement confirmed for Nightingale departure',
    description:
      '6 humans, 3 support agents. Commander Shepard (CO), Chief Vega (logistics), Pilot Nakamura (nav), Engineer Park (propulsion), Medic Reyes, Specialist Amara. Agents: autobot_lumen, cargo_AI_orion, nav_system_kepler.',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'commander_shepard',
    topic: 'crew',
    significance: 8,
    tags: ['crew'],
    created_at: hoursAgo(8),
  },
  {
    id: 'pkg_oort_004',
    project_id: 'proj_oort_resupply',
    title: '[KEY 9] Fuel cell QA pass — all 40 units cleared for deep-space transit',
    description: 'Thermal cycling, pressure integrity, isotope purity all within mission spec. Three units flagged for secondary review; all three passed.',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'cargo_AI_orion',
    topic: 'quality',
    significance: 9,
    decisions: ['Accept units 17, 23, 31 after secondary review — flagged only for cosmetic casing wear'],
    created_at: hoursAgo(14),
  },
  {
    id: 'pkg_oort_005',
    project_id: 'proj_oort_resupply',
    title: '[SIG 7] Reaction mass topped off at Ceres — 1,440 tons loaded',
    description: 'Full tank minus 6% safety margin. Sufficient for 3 full Europa round-trips without refuel.',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'engineer_park',
    topic: 'propulsion',
    significance: 7,
    created_at: hoursAgo(19),
  },
  {
    id: 'pkg_oort_006',
    project_id: 'proj_oort_resupply',
    title: '[auto] cargo: bay 3 temp log synced (-40.1C avg, -38.9C peak)',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'cargo_AI_orion',
    artifact_type: 'auto-deposit',
    significance: 1,
    created_at: hoursAgo(21),
  },
  {
    id: 'pkg_oort_007',
    project_id: 'proj_oort_resupply',
    title: '[KEY 10] Nightingale launch window OPEN — departure 0400 station time',
    description:
      'All systems green. Lagrange skip geometry favorable for next 38 hours. Weather clear through heliopause. Launch coordinator cleared manifest 4418.',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'commander_shepard',
    topic: 'launch',
    artifact_type: 'milestone',
    significance: 10,
    handoff_note: 'Nightingale is now inbound to Europa. Next checkpoint: L-5 skip insertion (T+18h).',
    created_at: hoursAgo(26),
  },
  {
    id: 'pkg_oort_008',
    project_id: 'proj_oort_resupply',
    title: '[SIG 6] Medical crates inventory: -2 vials anti-rad serum from manifest',
    description: 'Initial count flagged 12 crates but recount shows 10. Crossref with Ceres medical revealed two crates pulled by station chief for local emergency.',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'medic_reyes',
    topic: 'medical',
    significance: 6,
    decisions: ['Proceed with 10 crates — still exceeds mission minimum by 60%'],
    created_at: hoursAgo(32),
  },
  {
    id: 'pkg_oort_009',
    project_id: 'proj_oort_resupply',
    title: '[auto] nav: trajectory checkpoint T-02:45 synced',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'nav_system_kepler',
    artifact_type: 'auto-deposit',
    significance: 1,
    created_at: hoursAgo(35),
  },
  {
    id: 'pkg_oort_010',
    project_id: 'proj_oort_resupply',
    title: '[SIG 7] Hull plating source — Ceres foundry Batch G7 all gamma-rated',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'cargo_AI_orion',
    significance: 7,
    created_at: daysAgo(2),
  },
  {
    id: 'pkg_oort_011',
    project_id: 'proj_oort_resupply',
    title: '[KEY 9] Contract signed — Europa Dry Dock pays 2.4M credits on delivery',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'chief_vega',
    topic: 'commerce',
    significance: 9,
    created_at: daysAgo(3),
  },
  {
    id: 'pkg_oort_012',
    project_id: 'proj_oort_resupply',
    title: '[SIG 8] Insurance underwriter approved — 3.1M credit policy, 0.8% premium',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'chief_vega',
    significance: 8,
    created_at: daysAgo(4),
  },
  {
    id: 'pkg_oort_013',
    project_id: 'proj_oort_resupply',
    title: '[auto] cargo: bay 4 pressure seal test PASS',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'cargo_AI_orion',
    artifact_type: 'auto-deposit',
    significance: 1,
    created_at: daysAgo(5),
  },
  {
    id: 'pkg_oort_014',
    project_id: 'proj_oort_resupply',
    title: '[SIG 7] Crew debrief from Manifest 4417 — Titan run completed clean',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'pilot_nakamura',
    significance: 7,
    created_at: daysAgo(7),
  },
  {
    id: 'pkg_oort_015',
    project_id: 'proj_oort_resupply',
    title: '[SIG 6] Propulsion telemetry baseline for Nightingale updated',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'nav_system_kepler',
    significance: 6,
    created_at: daysAgo(9),
  },
  {
    id: 'pkg_oort_016',
    project_id: 'proj_oort_resupply',
    title: '[KEY 10] Oort Resupply Corridor Q3 charter renewed — 4 additional Nightingale-class hulls',
    description: 'Board approved expansion after Q2 margin performance. Fleet now at 11 active hulls on this route.',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'commander_shepard',
    topic: 'strategy',
    artifact_type: 'decision',
    significance: 10,
    decisions: ['Expand fleet to 11 active hulls', 'Prioritize deuterium contracts over general-freight mix'],
    created_at: daysAgo(11),
  },
  {
    id: 'pkg_oort_017',
    project_id: 'proj_oort_resupply',
    title: '[SIG 8] Route map updated — L-4/L-5 skip priority reversed after turbulence data',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'nav_system_kepler',
    significance: 8,
    created_at: daysAgo(12),
  },
  {
    id: 'pkg_oort_018',
    project_id: 'proj_oort_resupply',
    title: '[auto] logistics: weekly fuel-consumption digest',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'cargo_AI_orion',
    artifact_type: 'auto-deposit',
    significance: 1,
    created_at: daysAgo(13),
  },

  // ========== Kepler-442b Mining Run
  {
    id: 'pkg_kepler_001',
    project_id: 'proj_kepler_mining',
    title: '[KEY 10] Kepler-442b ore sample analysis — rare-earth concentrations 3.2x expected',
    description:
      'Core samples from the Mariana-Deep shaft returned neodymium, dysprosium, and terbium in concentrations three times the pre-mission geological model predicted. Revises projected 5-year yield upward by ~180%.',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'geology_AI_strabo',
    topic: 'geology',
    artifact_type: 'milestone',
    significance: 10,
    handoff_note:
      'Kepler board needs to revisit extraction rate plan — we are capacity-constrained on transport, not on ore. Recommend scaling hauler fleet.',
    decisions: ['Expand shaft from 4 drills to 8', 'Triple surveyor rotation at Mariana-Deep'],
    questions: [
      'Can Ceres refinery absorb 180% more rare-earth throughput without new bay builds?',
      'Is our insurance coverage adequate given the revised mission value?',
    ],
    tags: ['geology', 'priority'],
    created_at: minutesAgo(47),
  },
  {
    id: 'pkg_kepler_002',
    project_id: 'proj_kepler_mining',
    title: '[KEY 9] Hauler Valkyrie-7 docked at Ceres — 840 tons ore delivered',
    description: 'Full bay offload complete in 11.2 hours. Refinery assay pending.',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'pilot_nakamura',
    significance: 9,
    created_at: hoursAgo(5),
  },
  {
    id: 'pkg_kepler_003',
    project_id: 'proj_kepler_mining',
    title: '[SIG 8] Drill-3 head replacement complete — back online at 94% output',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'engineer_park',
    topic: 'mining',
    significance: 8,
    created_at: hoursAgo(9),
  },
  {
    id: 'pkg_kepler_004',
    project_id: 'proj_kepler_mining',
    title: '[SIG 7] Surveyor rotation schedule — next wave lands T+12h',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'commander_shepard',
    significance: 7,
    created_at: hoursAgo(14),
  },
  {
    id: 'pkg_kepler_005',
    project_id: 'proj_kepler_mining',
    title: '[KEY 10] Kepler-442b mining rights renewed — 20 year extension',
    description: 'Interstellar Extraction Authority signed extension after Q2 environmental compliance audit. No new restrictions.',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'commander_shepard',
    topic: 'legal',
    artifact_type: 'decision',
    significance: 10,
    handoff_note: 'Lock in long-term contracts now while rights are secured.',
    created_at: hoursAgo(20),
  },
  {
    id: 'pkg_kepler_006',
    project_id: 'proj_kepler_mining',
    title: '[auto] mining: shaft-B yield log (127 tons/hr avg)',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'geology_AI_strabo',
    artifact_type: 'auto-deposit',
    significance: 1,
    created_at: hoursAgo(23),
  },
  {
    id: 'pkg_kepler_007',
    project_id: 'proj_kepler_mining',
    title: '[SIG 8] Ore-handling robot fleet upgraded — cycle time down 18%',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'cargo_AI_orion',
    significance: 8,
    created_at: daysAgo(1),
  },
  {
    id: 'pkg_kepler_008',
    project_id: 'proj_kepler_mining',
    title: '[SIG 6] Dust-storm forecast — surface ops suspended 36h window',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'weather_AI_aeolus',
    significance: 6,
    created_at: daysAgo(2),
  },
  {
    id: 'pkg_kepler_009',
    project_id: 'proj_kepler_mining',
    title: '[KEY 9] New drill rig "Basilisk" commissioned at Mariana-Deep',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'engineer_park',
    significance: 9,
    created_at: daysAgo(4),
  },
  {
    id: 'pkg_kepler_010',
    project_id: 'proj_kepler_mining',
    title: '[SIG 7] Refinery yield delta — Q2 actuals beat forecast by 11%',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'chief_vega',
    significance: 7,
    created_at: daysAgo(6),
  },
  {
    id: 'pkg_kepler_011',
    project_id: 'proj_kepler_mining',
    title: '[auto] cargo: hauler schedule sync complete',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'cargo_AI_orion',
    artifact_type: 'auto-deposit',
    significance: 1,
    created_at: daysAgo(8),
  },
  {
    id: 'pkg_kepler_012',
    project_id: 'proj_kepler_mining',
    title: '[SIG 8] Environmental impact report filed — no violations',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'specialist_amara',
    significance: 8,
    created_at: daysAgo(10),
  },
  {
    id: 'pkg_kepler_013',
    project_id: 'proj_kepler_mining',
    title: '[SIG 6] Crew rotation off Kepler — 14 returning to Ceres for R&R',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'medic_reyes',
    significance: 6,
    created_at: daysAgo(12),
  },
  {
    id: 'pkg_kepler_014',
    project_id: 'proj_kepler_mining',
    title: '[KEY 10] Mariana-Deep shaft opened — first ore sample extracted',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'engineer_park',
    artifact_type: 'milestone',
    significance: 10,
    created_at: daysAgo(14),
  },

  // ========== Ceres Station Ops
  {
    id: 'pkg_ceres_001',
    project_id: 'proj_ceres_station',
    title: '[KEY 10] Dry Dock Bay 7 overhaul complete — ready for Valkyrie-class hulls',
    description:
      'Upgrade adds 40m clearance, thermal decoupling bay, and new mag-gantry. Can now service Valkyrie and future Leviathan-class freighters. Commissioning walkthrough passed inspection.',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'engineer_park',
    topic: 'infrastructure',
    artifact_type: 'milestone',
    significance: 10,
    handoff_note: 'Schedule first Valkyrie-class overhaul for Q3. Nightingale fleet will be the inaugural tenant.',
    created_at: hoursAgo(4),
  },
  {
    id: 'pkg_ceres_002',
    project_id: 'proj_ceres_station',
    title: '[KEY 9] Station water-recycling loop at 99.4% efficiency — record high',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'env_AI_hydros',
    topic: 'life-support',
    significance: 9,
    created_at: hoursAgo(11),
  },
  {
    id: 'pkg_ceres_003',
    project_id: 'proj_ceres_station',
    title: '[SIG 8] Crew rotation schedule — 240 inbound, 210 departing over next 7 days',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'commander_shepard',
    significance: 8,
    created_at: hoursAgo(18),
  },
  {
    id: 'pkg_ceres_004',
    project_id: 'proj_ceres_station',
    title: '[SIG 7] Airlock-4 seal inspection — passed with advisory on gasket wear',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'engineer_park',
    significance: 7,
    created_at: daysAgo(1),
  },
  {
    id: 'pkg_ceres_005',
    project_id: 'proj_ceres_station',
    title: '[KEY 9] Solar array 3 re-panel complete — station output back to 100%',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'specialist_amara',
    significance: 9,
    created_at: daysAgo(2),
  },
  {
    id: 'pkg_ceres_006',
    project_id: 'proj_ceres_station',
    title: '[auto] env: CO2 scrubber cycle logged',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'env_AI_hydros',
    artifact_type: 'auto-deposit',
    significance: 1,
    created_at: daysAgo(3),
  },
  {
    id: 'pkg_ceres_007',
    project_id: 'proj_ceres_station',
    title: '[SIG 8] Medical bay expansion greenlit — 40 new acute-care bunks',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'medic_reyes',
    significance: 8,
    created_at: daysAgo(5),
  },
  {
    id: 'pkg_ceres_008',
    project_id: 'proj_ceres_station',
    title: '[SIG 7] Station refit plan Q3 — budget approved, scope locked',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'commander_shepard',
    significance: 7,
    created_at: daysAgo(8),
  },
  {
    id: 'pkg_ceres_009',
    project_id: 'proj_ceres_station',
    title: '[SIG 6] Hydroponics yield — tomato crop +22% on new LED cycle',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'env_AI_hydros',
    significance: 6,
    created_at: daysAgo(10),
  },
  {
    id: 'pkg_ceres_010',
    project_id: 'proj_ceres_station',
    title: '[auto] docking: bay-rotation weekly summary',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'cargo_AI_orion',
    artifact_type: 'auto-deposit',
    significance: 1,
    created_at: daysAgo(11),
  },
  {
    id: 'pkg_ceres_011',
    project_id: 'proj_ceres_station',
    title: '[KEY 10] Ceres long-range comms upgrade ONLINE — latency to Earth down 14%',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'comms_AI_hermes',
    artifact_type: 'milestone',
    significance: 10,
    created_at: daysAgo(13),
  },

  // ========== Europa Deep Survey
  {
    id: 'pkg_europa_001',
    project_id: 'proj_europa_survey',
    title: '[KEY 10] Subsurface sonar returned — liquid ocean confirmed at 18km depth',
    description:
      'Penetrating sonar pass over Conamara Chaos confirms ocean interface at 18.4km beneath ice crust. Return signature suggests unexpected thermal vents cluster.',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'geology_AI_strabo',
    topic: 'science',
    artifact_type: 'milestone',
    significance: 10,
    handoff_note: 'Prioritize ROV drop over the thermal vent cluster. Rewrite sample plan around vent plumes.',
    decisions: ['Shift ROV Drop Site A 4km east to align with vent cluster'],
    questions: ['Thermal vents imply chemical gradient — do we have the biosignature kit stocked for plume sampling?'],
    created_at: minutesAgo(90),
  },
  {
    id: 'pkg_europa_002',
    project_id: 'proj_europa_survey',
    title: '[KEY 9] ROV Naiad-3 deployed — descending through ice shaft',
    status: 'in_progress',
    actor_type: 'human',
    actor_id: 'specialist_amara',
    significance: 9,
    created_at: hoursAgo(6),
  },
  {
    id: 'pkg_europa_003',
    project_id: 'proj_europa_survey',
    title: '[SIG 8] Ice core samples returned — first spectral analysis clean',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'geology_AI_strabo',
    significance: 8,
    created_at: hoursAgo(15),
  },
  {
    id: 'pkg_europa_004',
    project_id: 'proj_europa_survey',
    title: '[SIG 7] Surface camp Alpha established — 4-person crew rotation',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'commander_shepard',
    significance: 7,
    created_at: daysAgo(2),
  },
  {
    id: 'pkg_europa_005',
    project_id: 'proj_europa_survey',
    title: '[auto] telemetry: Naiad-3 depth 4.2km',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'telemetry_AI_iris',
    artifact_type: 'auto-deposit',
    significance: 1,
    created_at: daysAgo(3),
  },
  {
    id: 'pkg_europa_006',
    project_id: 'proj_europa_survey',
    title: '[KEY 9] Mission charter approved by Planetary Protection Office',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'specialist_amara',
    significance: 9,
    created_at: daysAgo(6),
  },
  {
    id: 'pkg_europa_007',
    project_id: 'proj_europa_survey',
    title: '[SIG 6] Rendezvous with Nightingale confirmed T+7 days',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'pilot_nakamura',
    significance: 6,
    created_at: daysAgo(9),
  },

  // ========== Titan Relay Network
  {
    id: 'pkg_titan_001',
    project_id: 'proj_titan_relay',
    title: '[KEY 10] Relay sat 7 OFFLINE — comms rerouted through sat 12 backup',
    description: 'Unexpected loss of carrier signal from Relay-7 at 03:22 station. Autobot Lumen automatically rerouted traffic through Relay-12 before crew woke. Dispatch repair drone.',
    status: 'in_progress',
    actor_type: 'agent',
    actor_id: 'comms_AI_hermes',
    topic: 'comms',
    artifact_type: 'incident',
    significance: 10,
    handoff_note: 'Ship repair drone from Ceres on next courier run. Until then sat 12 is bearing extra load — monitor overflow.',
    decisions: ['Auto-reroute kept. Do not revert until sat 7 service pass completes.'],
    questions: ['Is sat 7 failure thermal, power, or hardware? No telemetry returning.'],
    created_at: minutesAgo(130),
  },
  {
    id: 'pkg_titan_002',
    project_id: 'proj_titan_relay',
    title: '[SIG 8] Sat 12 load at 78% capacity — within thermal envelope',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'comms_AI_hermes',
    significance: 8,
    created_at: hoursAgo(4),
  },
  {
    id: 'pkg_titan_003',
    project_id: 'proj_titan_relay',
    title: '[KEY 9] Constellation phase 2 deployment complete — 18 sats on orbit',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'pilot_nakamura',
    artifact_type: 'milestone',
    significance: 9,
    created_at: daysAgo(2),
  },
  {
    id: 'pkg_titan_004',
    project_id: 'proj_titan_relay',
    title: '[SIG 7] Uplink latency baseline — Titan-Ceres 1.4s p50',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'telemetry_AI_iris',
    significance: 7,
    created_at: daysAgo(5),
  },
  {
    id: 'pkg_titan_005',
    project_id: 'proj_titan_relay',
    title: '[auto] comms: daily uptime digest',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'comms_AI_hermes',
    artifact_type: 'auto-deposit',
    significance: 1,
    created_at: daysAgo(8),
  },

  // ========== Helios Freight Line (archived)
  {
    id: 'pkg_helios_001',
    project_id: 'proj_helios_freight',
    title: '[KEY 10] Helios Freight Line decommissioned — Helios-3 incident final report',
    description: 'After the Helios-3 coronal breach, board ruled the solar-orbit freight line unsustainable at current hull ratings. All remaining contracts migrated to Oort corridor.',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'commander_shepard',
    artifact_type: 'decision',
    significance: 10,
    created_at: daysAgo(45),
  },
  {
    id: 'pkg_helios_002',
    project_id: 'proj_helios_freight',
    title: '[KEY 9] Helios-3 incident — hull breach at perihelion, crew evac successful',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'commander_shepard',
    significance: 9,
    created_at: daysAgo(52),
  },
  {
    id: 'pkg_helios_003',
    project_id: 'proj_helios_freight',
    title: '[SIG 7] Final Helios manifest delivered — contracts migrating',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'chief_vega',
    significance: 7,
    created_at: daysAgo(60),
  },
];

// Map each project to the session callsign currently active in it so
// KEY/SIG packages from the mock set can be visually attributed. Declared
// before MOCK_PACKAGES below because `sessionFor` reads this table at
// module evaluation while building the fixtures.
const PROJECT_TO_SESSION: Record<string, string> = {
  proj_oort_resupply: 'sess_oort_001',
  proj_kepler_mining: 'sess_kepler_001',
  proj_titan_relay: 'sess_titan_001',
  proj_europa_survey: 'sess_europa_001',
  proj_ceres_station: 'sess_ceres_001',
};

// Link non-auto packages to the active session for their project so the
// callsign surfaces on the Timeline and the mock feels audit-coherent.
function sessionFor(p: PkgSpec): string | null {
  if (p.artifact_type === 'auto-deposit') return null;
  return PROJECT_TO_SESSION[p.project_id] ?? null;
}

export const MOCK_PACKAGES: PackageRow[] = PKGS.map((p) => ({
  id: p.id,
  project_id: p.project_id,
  title: p.title,
  description: p.description ?? null,
  status: p.status ?? 'complete',
  package_type: 'standard',
  review_type: 'none',
  parent_package_id: null,
  created_by_type: p.actor_type ?? 'human',
  created_by_id: p.actor_id ?? 'commander_shepard',
  session_id: sessionFor(p),
  tags: p.tags ?? [],
  open_questions: p.questions ?? [],
  decisions_made: p.decisions ?? [],
  handoff_note: p.handoff_note ?? null,
  deliverables: [],
  context_md: null,
  significance: p.significance ?? 5,
  topic: p.topic ?? null,
  artifact_type: p.artifact_type ?? null,
  created_at: p.created_at,
}));

export const MOCK_SESSIONS: SessionRow[] = [
  {
    id: 'sess_oort_001',
    project_id: 'proj_oort_resupply',
    actor_type: 'human',
    actor_id: 'chief_vega',
    callsign: 'coral-heron',
    started_at: minutesAgo(18),
    ended_at: null,
  },
  {
    id: 'sess_kepler_001',
    project_id: 'proj_kepler_mining',
    actor_type: 'agent',
    actor_id: 'geology_AI_strabo',
    callsign: 'molten-fox',
    started_at: minutesAgo(52),
    ended_at: null,
  },
  {
    id: 'sess_titan_001',
    project_id: 'proj_titan_relay',
    actor_type: 'agent',
    actor_id: 'comms_AI_hermes',
    callsign: 'quartz-kestrel',
    started_at: hoursAgo(2),
    ended_at: null,
  },
  {
    id: 'sess_europa_001',
    project_id: 'proj_europa_survey',
    actor_type: 'human',
    actor_id: 'specialist_amara',
    callsign: 'jade-albatross',
    started_at: hoursAgo(6),
    ended_at: hoursAgo(1),
  },
  {
    id: 'sess_ceres_001',
    project_id: 'proj_ceres_station',
    actor_type: 'human',
    actor_id: 'engineer_park',
    callsign: 'bronze-badger',
    started_at: hoursAgo(12),
    ended_at: hoursAgo(4),
  },
];

/** Lookup: session_id → callsign, for Timeline/UI rendering. */
export const CALLSIGN_BY_SESSION_ID: Record<string, string> = Object.fromEntries(
  MOCK_SESSIONS.filter((s) => s.callsign).map((s) => [s.id, s.callsign as string]),
);

// Rotation pool for the simulated live feed. Each entry becomes a fresh
// package once a minute or so, inserted at the top of the stream so the
// dashboard looks alive on first view.
export const LIVE_FEED_POOL: Array<Omit<PkgSpec, 'id' | 'created_at'>> = [
  {
    project_id: 'proj_oort_resupply',
    title: '[auto] nav: course micro-correction logged',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'nav_system_kepler',
    artifact_type: 'auto-deposit',
    significance: 1,
  },
  {
    project_id: 'proj_kepler_mining',
    title: '[SIG 7] Shaft-B yield spike — 148 tons/hr, 17% above baseline',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'geology_AI_strabo',
    topic: 'mining',
    significance: 7,
  },
  {
    project_id: 'proj_titan_relay',
    title: '[SIG 6] Sat 7 repair drone dispatched from Ceres',
    status: 'in_progress',
    actor_type: 'human',
    actor_id: 'engineer_park',
    significance: 6,
  },
  {
    project_id: 'proj_europa_survey',
    title: '[KEY 9] ROV Naiad-3 reached ocean interface — first plume sample acquired',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'specialist_amara',
    significance: 9,
    handoff_note: 'Sample is in cryo-hold. Coordinate return transport with next Nightingale run.',
  },
  {
    project_id: 'proj_ceres_station',
    title: '[auto] env: atmosphere cycle digest synced',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'env_AI_hydros',
    artifact_type: 'auto-deposit',
    significance: 1,
  },
  {
    project_id: 'proj_oort_resupply',
    title: '[SIG 8] Nightingale passed L-5 skip cleanly — back on nominal trajectory',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'nav_system_kepler',
    significance: 8,
  },
  {
    project_id: 'proj_kepler_mining',
    title: '[auto] mining: ore bin 14 sealed for transit',
    status: 'complete',
    actor_type: 'agent',
    actor_id: 'cargo_AI_orion',
    artifact_type: 'auto-deposit',
    significance: 1,
  },
  {
    project_id: 'proj_titan_relay',
    title: '[KEY 10] Sat 7 service pass complete — carrier signal restored',
    status: 'complete',
    actor_type: 'human',
    actor_id: 'engineer_park',
    artifact_type: 'milestone',
    significance: 10,
    handoff_note: 'Reverting sat 12 back to normal load. Close incident ticket.',
  },
];
